"""
Seed script — converts the Haniya XLSX dataset into a hardcoded Python module.

Reads:  backend/YouthPay_Hackathon_Dataset_Haniya_Final.xlsx (sheet: Structured_Transactions)
Writes: backend/data/transactions.py  (a single TRANSACTIONS list of typed dicts)

This is the single source of truth for every downstream step. Run once:
    python scripts/seed.py
Verify:
    python -c "from data.transactions import TRANSACTIONS; print(len(TRANSACTIONS))"  # -> 160
"""

import openpyxl
from pathlib import Path

# Resolve paths relative to the backend root (parent of this script's dir),
# so the script behaves identically no matter where it is invoked from.
BACKEND_ROOT = Path(__file__).resolve().parent.parent
XLSX_PATH = BACKEND_ROOT / "YouthPay_Hackathon_Dataset_Haniya_Final.xlsx"
OUTPUT_PATH = BACKEND_ROOT / "data" / "transactions.py"
SHEET_NAME = "Structured_Transactions"


def main() -> None:
    wb = openpyxl.load_workbook(XLSX_PATH, read_only=True)
    ws = wb[SHEET_NAME]
    rows = list(ws.iter_rows(values_only=True))

    headers = rows[0]
    data = []
    for i, row in enumerate(rows[1:], 1):
        record = dict(zip(headers, row))
        record["id"] = i
        # Normalize date_time to ISO 8601: "2026-06-01 09:00" -> "2026-06-01T09:00:00"
        if record.get("date_time"):
            record["date_time"] = str(record["date_time"]).replace(" ", "T") + ":00"
        # Keep amount_pkr as a float for consistent downstream math
        if record.get("amount_pkr") is not None:
            record["amount_pkr"] = float(record["amount_pkr"])
        data.append(record)

    # Write as a Python module: one dict literal per line for clean diffs.
    lines = [
        '"""Auto-generated by scripts/seed.py. Do not edit by hand."""\n\n',
        "TRANSACTIONS = [\n",
    ]
    for d in data:
        lines.append(f"    {d!r},\n")
    lines.append("]\n")

    OUTPUT_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"Seeded {len(data)} transactions -> {OUTPUT_PATH.relative_to(BACKEND_ROOT)}")


if __name__ == "__main__":
    main()
